In [1]:
import numpy as np
import pandas as pd
import pypsa

import sys
from pathlib import Path

sys.path.insert(0, str(Path("src")))

from src import network_builder
from src import util
from util import annualized_capex

In [2]:
data = pd.read_csv("data/clean_data.csv")

In [3]:
snapshots = data.index
nHours = len(snapshots)

load = pd.DataFrame(index=snapshots)
load["reg1"] = data["load_mw"] * .3
load["reg2"] = data["load_mw"] *  .5
load["reg3"] = data["load_mw"] * .7

solar = pd.DataFrame(index=snapshots)
solar["reg1"] = data["ca_pv_cf"]
solar["reg2"] = data["az_pv_cf"]
solar["reg3"] = data["nv_pv_cf"]

wind = pd.DataFrame(index=snapshots)
wind["reg1"] = data["ca_wind_cf"]
wind["reg2"] = data["pnw_wind_cf"]
wind["reg3"] = data["wy_wind_cf"]

In [4]:
total_load_mwh = load.sum().sum()
baseline_emissions = total_load_mwh * 0.4
co2_cap = baseline_emissions * 0.05   # for a 95% reduction


ldes_cost_case = "medium"
transmission_friction = "low"
ldes_duration_hours = 24


ldes_cost_multipliers = {
        "low": 0.70,
        "medium": 1.00,
        "high": 1.40,
    }

ldes_base_capex_per_mw = 1_800_000
    transmission_base_capex_per_mw = 400_000

In [6]:
n = network_builder.build_network(snapshots, load, wind, solar, co2_cap, ldes_cost_case, transmission_friction, ldes_duration_hours)

In [7]:
RESOLUTION = 1
n.set_snapshots(n.snapshots[::RESOLUTION])
n.snapshot_weightings.loc[:, :] = RESOLUTION

n.optimize()

/var/folders/t_/32_5y8z906v9c0l8qphz6hx00000gn/T/ipykernel_68507/243138191.py:5: FutureWarning:

The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.

WARNING:pypsa.consistency:The following buses have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['reg1', 'reg2', 'reg3'], dtype='object', name='name')
WARNING:pypsa.consistency:Encountered nan's in static data for columns ['max_growth', 'max_relative_growth'] of component 'Carrier'.
WARNING:pypsa.consistency:The following links have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['tx_reg1_reg2', 'tx_reg1_reg3', 'tx_reg2_reg3'], dtype='object', name='name')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|████████████████████| 16/16 [00:00<00:00, 103.24it/s]
Writing continuous variables.: 100%|█████████████| 8/8 [00:00<00:00, 572.08it/s]
INFO:linopy.io: Writing time: 0.29s

Running HiGHS 1.13.1 (git hash: n/a): Copyright (c) 2026 under MIT licence terms
LP linopy-problem-kox2ect8 has 603907 rows; 262578 cols; 1246087 nonzeros
Coefficient ranges:
  Matrix  [1e-03, 2e+01]
  Cost    [1e+02, 2e+05]
  Bound   [0e+00, 0e+00]
  RHS     [5e+03, 7e+06]
WARNING: Problem has some excessively large row bounds
WARNING:    Consider scaling the    bounds by 1e-1, or setting the user_bound_scale option to -3
Presolving model
327110 rows, 248359 cols, 955071 nonzeros  0s
Dependent equations search running on 78768 equations with time limit of 1000.00s
Dependent equations search removed 0 rows and 0 nonzeros in 0.01s (limit = 1000.00s)
327110 rows, 248359 cols, 955071 nonzeros  0s
Presolve reductions: rows 327110(-276797); columns 248359(-14219); nonzeros 955071(-291016)
Solving the presolved LP
Using dual simplex solver
  Iteration        Objective     Infeasibilities num(sum)
          0     0.0000000000e+00 Pr: 26256(2.59738e+08) 0.4s
      32390     7.9024420119e+09 Pr: 105972(5.82746e+09); Du: 0(1.54519e-06) 6.2s
      38505     7.9026372753e+09 Pr: 106647(9.48671e+09); Du: 0(1.45445e-06) 12.0s
      44050     7.9029906171e+09 Pr: 107083(1.65083e+10); Du: 0(1.45445e-06) 18.0s
      48379     7.9032942436e+09 Pr: 107719(2.15794e+10); Du: 0(1.45445e-06) 23.4s
      52276     7.9036935029e+09 Pr: 108013(2.91619e+10); Du: 0(1.45445e-06) 28.8s
      55683     7.9040418201e+09 Pr: 108408(3.71151e+10); Du: 0(1.34054e-06) 33.9s
      59226     7.9043979070e+09 Pr: 108754(4.26917e+10); Du: 0(1.38011e-06) 39.6s
      62700     7.9047910717e+09 Pr: 108992(4.96666e+10); Du: 0(1.3784e-06) 45.7s
      65888     7.9051736145e+09 Pr: 109310(5.56728e+10); Du: 0(1.22569e-06) 51.6s
      69253     7.9057884856e+09 Pr: 109683(6.65008e+10); Du: 0(1.22569e-06) 58.1s
      72199     8.5878316525e+09 Pr: 94134(5.21643e+09); Du: 0(1.01842e-06) 64.2s
      74543     9.9008755457e+09 Pr: 151227(1.36764e+10); Du: 0(1.01842e-06) 70.6s
      76650     1.0957716417e+10 Pr: 68098(4.25293e+10); Du: 0(1.01842e-06) 76.7s
      78617     1.1329180788e+10 Pr: 68269(2.00597e+10); Du: 0(1.01842e-06) 82.8s
      81452     1.1778375021e+10 Pr: 86130(2.83407e+10); Du: 0(8.85166e-07) 90.2s
      83591     1.2708942957e+10 Pr: 85450(7.55508e+10); Du: 0(8.82589e-07) 96.5s
      86035     1.3390311601e+10 Pr: 113045(1.01936e+11); Du: 0(8.4302e-07) 102.2s
      88241     1.4813821614e+10 Pr: 83178(2.74346e+10); Du: 0(8.4302e-07) 108.1s
      90672     1.6207396399e+10 Pr: 127942(6.85597e+10); Du: 0(8.4302e-07) 114.7s
      95340     1.6724292111e+10 Pr: 160131(9.35184e+10); Du: 0(8.0301e-07) 123.8s
     100096     1.6765122354e+10 Pr: 178924(2.45618e+11); Du: 0(7.53983e-07) 133.3s
     102508     1.6765168046e+10 Pr: 178927(2.48647e+11); Du: 0(7.88753e-07) 138.5s
     106546     1.6765250116e+10 Pr: 179117(2.53536e+11); Du: 0(8.01227e-07) 147.8s
     110137     1.6765332613e+10 Pr: 179051(2.56526e+11); Du: 0(9.12369e-07) 156.4s
     113878     1.6765454433e+10 Pr: 178997(2.6228e+11); Du: 0(9.12369e-07) 165.4s
     117072     1.6765593388e+10 Pr: 179041(2.68326e+11); Du: 0(5.95078e-07) 173.4s
     120361     1.6765717149e+10 Pr: 179246(2.74024e+11); Du: 0(5.97722e-07) 181.8s
     123752     1.6765850903e+10 Pr: 179334(2.78986e+11); Du: 0(5.97722e-07) 190.8s
     126898     1.6765975109e+10 Pr: 179481(2.84753e+11); Du: 0(6.42135e-07) 199.3s
     129795     1.6766070191e+10 Pr: 179429(2.90313e+11); Du: 0(4.87489e-07) 207.4s
     131637     1.6766119887e+10 Pr: 179554(2.91361e+11); Du: 0(5.58823e-07) 212.7s
     134156     1.6766191196e+10 Pr: 179642(2.97619e+11); Du: 0(4.45642e-07) 220.5s
     136153     1.6766254578e+10 Pr: 179582(3.00413e+11); Du: 0(5.84042e-07) 227.0s
     138557     1.6766360570e+10 Pr: 179494(3.04814e+11); Du: 0(4.57793e-07) 234.8s
     140871     1.6766496373e+10 Pr: 179506(3.11229e+11); Du: 0(4.68635e-07) 242.5s
     143569     1.6766608496e+10 Pr: 179452(3.15492e+11); Du: 0(4.76196e-07) 251.4s
     146025     1.6766701137e+10 Pr: 179403(3.22135e+11); Du: 0(5.99752e-07) 259.7s
     147922     1.7433652797e+10 Pr: 165441(2.26432e+12); Du: 0(4.57793e-07) 267.2s
     149321     1.8632376977e+10 Pr: 135877(2.60888e+11); Du: 0(5.16717e-07) 273.5s
     151016     1.9209617912e+10 Pr: 155178(3.648e+11); Du: 0(5.5831e-07) 280.5s
     152565     2.0111832057e+10 Pr: 125000(2.31684e+11); Du: 0(5.9893e-07) 288.0s
     153857     2.0857473018e+10 Pr: 128381(4.83724e+11); Du: 0(6.16389e-07) 294.8s
     155075     2.1815120567e+10 Pr: 125311(1.04649e+11); Du: 0(5.72716e-07) 301.2s
     157493     2.2637336585e+10 Pr: 147900(1.16095e+11); Du: 0(5.72716e-07) 312.6s
     158642     2.3143101851e+10 Pr: 131417(1.1243e+11); Du: 0(5.72716e-07) 317.8s
     159861     2.3578905417e+10 Pr: 108471(5.02571e+10); Du: 0(4.73023e-07) 323.1s
     160990     2.3890194402e+10 Pr: 90650(1.0186e+11); Du: 0(4.73023e-07) 328.2s
     162096     2.4073102002e+10 Pr: 130864(3.43861e+11); Du: 0(4.73023e-07) 333.2s
     164975     2.4505422566e+10 Pr: 151552(2.7315e+10); Du: 0(5.98539e-07) 346.0s
     166489     2.4715071733e+10 Pr: 80398(3.32191e+10); Du: 0(5.98539e-07) 352.6s
     169474     2.5107056576e+10 Pr: 144668(1.128e+11); Du: 0(6.01223e-07) 362.7s
     171652     2.5310910731e+10 Pr: 94829(1.4825e+11); Du: 0(6.01223e-07) 370.4s
     172902     2.5457189953e+10 Pr: 110830(1.39818e+10); Du: 0(5.54393e-07) 375.7s
     175227     2.5746244874e+10 Pr: 123631(2.79275e+10); Du: 0(5.54393e-07) 385.1s
     177583     2.5920109948e+10 Pr: 136193(5.65739e+10); Du: 0(4.62689e-07) 391.3s
     180913     2.6690839718e+10 Pr: 169617(4.75477e+10); Du: 0(4.29392e-07) 403.0s
     182709     2.6912489832e+10 Pr: 150046(4.60364e+10); Du: 0(4.54333e-07) 412.6s
     183580     2.7048794806e+10 Pr: 145961(7.06158e+10); Du: 0(5.52723e-07) 417.7s
     184673     2.7124593544e+10 Pr: 96980(8.0054e+10); Du: 0(7.28871e-07) 423.2s
     186426     2.7373059927e+10 Pr: 131728(7.551e+10); Du: 0(6.73036e-07) 432.7s
     187608     2.7494914336e+10 Pr: 146132(1.64255e+11); Du: 0(7.21025e-07) 438.7s
     188638     2.7585025850e+10 Pr: 162372(1.40393e+10); Du: 0(7.04612e-07) 445.0s
     189763     2.7761991313e+10 Pr: 149138(1.42085e+11); Du: 0(6.68119e-07) 451.0s
     190682     2.7914223075e+10 Pr: 154722(9.80918e+10); Du: 0(6.68119e-07) 456.5s
     191659     2.8114236763e+10 Pr: 129979(2.69624e+11); Du: 0(6.2013e-07) 461.8s
     193196     2.8339460197e+10 Pr: 165088(8.25241e+10); Du: 0(5.89781e-07) 470.0s
     195149     2.8583871072e+10 Pr: 126033(1.46705e+10); Du: 0(5.90187e-07) 479.8s
     196221     2.8668491290e+10 Pr: 127949(2.47839e+10); Du: 0(6.43953e-07) 485.4s
     197438     2.8879521526e+10 Pr: 128727(2.44414e+10); Du: 0(5.17916e-07) 491.8s
     198629     2.8982826326e+10 Pr: 151849(1.55452e+11); Du: 0(5.59676e-07) 498.2s
     199898     2.9136724394e+10 Pr: 116595(1.27184e+10); Du: 0(4.0908e-07) 504.7s
     201770     2.9510141484e+10 Pr: 137868(2.85391e+10); Du: 0(5.26304e-07) 515.0s
     202846     2.9645404737e+10 Pr: 158018(4.42522e+10); Du: 0(6.12166e-07) 520.6s
     204097     2.9764508847e+10 Pr: 120018(5.33413e+10); Du: 0(5.85855e-07) 526.9s
     205156     2.9902350761e+10 Pr: 116006(3.02897e+10); Du: 0(5.31689e-07) 532.6s
     206189     2.9986534650e+10 Pr: 149895(6.66808e+10); Du: 0(6.35959e-07) 537.9s
     207333     3.0063291795e+10 Pr: 123779(2.39546e+10); Du: 0(7.17927e-07) 543.5s
     208519     3.0138476746e+10 Pr: 112793(2.20019e+10); Du: 0(6.37169e-07) 548.9s
     209576     3.0255209227e+10 Pr: 147581(1.29103e+10); Du: 0(4.82699e-07) 554.1s
     211720     3.0446899932e+10 Pr: 110210(7.79698e+09); Du: 0(5.07941e-07) 564.7s
     212953     3.0562984933e+10 Pr: 144414(2.33313e+10); Du: 0(5.967e-07) 570.6s
     214032     3.0675426680e+10 Pr: 194547(3.70295e+10); Du: 0(6.80544e-07) 576.1s
     215286     3.0778355819e+10 Pr: 108753(9.18897e+09); Du: 0(5.7854e-07) 582.1s
     216469     3.0914096159e+10 Pr: 127792(5.68013e+10); Du: 0(5.74885e-07) 587.9s
     217515     3.1058469822e+10 Pr: 118238(1.15715e+10); Du: 0(5.74885e-07) 593.1s
     218534     3.1112313782e+10 Pr: 95481(7.16598e+10); Du: 0(5.55547e-07) 598.5s
     221009     3.1359896181e+10 Pr: 145039(5.29514e+10); Du: 0(7.52999e-07) 608.6s
     222068     3.1453151356e+10 Pr: 148054(4.96344e+10); Du: 0(6.33609e-07) 614.1s
     223270     3.1545254553e+10 Pr: 95453(2.21611e+10); Du: 0(7.54426e-07) 619.4s
     224476     3.1672706292e+10 Pr: 146539(6.4301e+10); Du: 0(6.47751e-07) 625.5s
     225516     3.1819693146e+10 Pr: 125045(4.5234e+10); Du: 0(5.68412e-07) 631.2s
     226634     3.1913956517e+10 Pr: 130718(5.58893e+10); Du: 0(5.85722e-07) 636.5s
     227795     3.2020462105e+10 Pr: 140515(4.12833e+10); Du: 0(6.7624e-07) 642.1s
     229150     3.2116617957e+10 Pr: 127875(1.92582e+10); Du: 0(6.17452e-07) 648.2s
     231205     3.2311700701e+10 Pr: 132993(1.04414e+10); Du: 0(5.96822e-07) 658.5s
     233320     3.2424044770e+10 Pr: 124493(6.06716e+10); Du: 0(6.92111e-07) 667.8s
     234437     3.2481045500e+10 Pr: 129633(1.27295e+10); Du: 0(7.09974e-07) 673.2s
     235492     3.2557400861e+10 Pr: 147563(2.54698e+10); Du: 0(6.92111e-07) 678.2s
     236571     3.2657837149e+10 Pr: 126620(1.33654e+10); Du: 0(9.11142e-07) 683.3s
     238386     3.2830128195e+10 Pr: 164076(1.365e+10); Du: 0(8.574e-07) 692.8s
     240011     3.2988311292e+10 Pr: 141847(1.14152e+10); Du: 0(8.92235e-07) 701.7s
     241222     3.3084675419e+10 Pr: 144176(1.29613e+10); Du: 0(8.84405e-07) 706.9s
     242300     3.3194155701e+10 Pr: 168537(8.65202e+10); Du: 0(9.20524e-07) 711.9s
     243453     3.3286585368e+10 Pr: 148508(1.3843e+10); Du: 0(1.04245e-06) 717.5s
     245534     3.3404411510e+10 Pr: 115556(5.71202e+10); Du: 0(1.12964e-06) 726.9s
     247458     3.3613482395e+10 Pr: 118825(9.89135e+09); Du: 0(9.45793e-07) 736.2s
     248564     3.3707972199e+10 Pr: 130700(2.48398e+10); Du: 0(8.48105e-07) 741.3s
     250778     3.3862581471e+10 Pr: 173438(1.21181e+11); Du: 0(9.40928e-07) 751.5s
     252826     3.4053514915e+10 Pr: 132593(4.16326e+10); Du: 0(1.00306e-06) 760.4s
     254167     3.4155229117e+10 Pr: 107982(8.21375e+09); Du: 0(9.95376e-07) 766.3s
     255556     3.4233589686e+10 Pr: 132153(3.55681e+10); Du: 0(8.46479e-07) 772.2s
     257001     3.4294630876e+10 Pr: 139811(4.70043e+10); Du: 0(7.65388e-07) 778.0s
     258255     3.4381432556e+10 Pr: 153193(8.20106e+09); Du: 0(8.86241e-07) 783.3s
     259402     3.4509122808e+10 Pr: 135033(1.67796e+10); Du: 0(1.21385e-06) 788.3s
     260584     3.4621915329e+10 Pr: 120011(1.30123e+10); Du: 0(1.06365e-06) 793.5s
     262593     3.4742957533e+10 Pr: 101041(7.41121e+09); Du: 0(1.06126e-06) 802.6s
     264773     3.4835581321e+10 Pr: 104609(1.02613e+10); Du: 0(1.09546e-06) 811.5s
     267043     3.5040917175e+10 Pr: 172021(8.16912e+10); Du: 0(8.71112e-07) 821.4s
     268218     3.5124437984e+10 Pr: 138466(1.55668e+10); Du: 0(1.05279e-06) 826.4s
     269610     3.5179305068e+10 Pr: 194775(4.57772e+10); Du: 0(1.26293e-06) 831.8s
     270934     3.5267064410e+10 Pr: 118670(6.19444e+09); Du: 0(1.3979e-06) 837.2s
     272172     3.5402321398e+10 Pr: 133772(2.04795e+11); Du: 0(1.25129e-06) 842.7s
     273489     3.5523691883e+10 Pr: 154084(5.00135e+10); Du: 0(1.33978e-06) 848.3s
     274802     3.5632232502e+10 Pr: 136499(5.85935e+10); Du: 0(1.47576e-06) 853.9s
     277209     3.5809629151e+10 Pr: 116629(1.78986e+10); Du: 0(1.30433e-06) 863.6s
     278689     3.5860551646e+10 Pr: 162809(3.82854e+10); Du: 0(1.63737e-06) 869.2s
     280083     3.5914479934e+10 Pr: 115284(2.56137e+10); Du: 0(2.07278e-06) 874.5s
     281643     3.5956902942e+10 Pr: 96171(1.20258e+10); Du: 0(1.82551e-06) 880.5s
     282967     3.6040922811e+10 Pr: 134001(2.56557e+10); Du: 0(1.52161e-06) 886.0s
     284326     3.6167082147e+10 Pr: 120224(8.97606e+09); Du: 0(1.42327e-06) 891.4s
     285823     3.6259110485e+10 Pr: 153428(7.83745e+09); Du: 0(1.44106e-06) 897.3s
     287081     3.6316368363e+10 Pr: 124679(9.70396e+09); Du: 0(1.3803e-06) 902.4s
     288507     3.6381675888e+10 Pr: 108298(1.30228e+10); Du: 0(1.45694e-06) 907.9s
     289849     3.6423920238e+10 Pr: 121459(7.43828e+09); Du: 0(1.3804e-06) 912.9s
     291087     3.6522956000e+10 Pr: 154715(1.60076e+10); Du: 0(1.37774e-06) 918.1s
     292632     3.6579932879e+10 Pr: 116157(8.61342e+09); Du: 0(1.13336e-06) 923.4s
     293953     3.6687558633e+10 Pr: 107363(4.48125e+09); Du: 0(1.21044e-06) 928.7s
     295366     3.6769307493e+10 Pr: 131123(2.35031e+10); Du: 0(1.20914e-06) 934.1s
     296855     3.6875523064e+10 Pr: 153147(3.89371e+10); Du: 0(1.41884e-06) 939.6s
     298295     3.6946764906e+10 Pr: 95705(7.92082e+09); Du: 0(1.80581e-06) 945.2s
     301018     3.7088272321e+10 Pr: 114899(2.36654e+10); Du: 0(2.1355e-06) 955.8s
     302579     3.7134706657e+10 Pr: 77604(4.77245e+09); Du: 0(1.97052e-06) 961.8s
     304105     3.7179220197e+10 Pr: 108251(1.645e+10); Du: 0(1.93586e-06) 967.1s
     305455     3.7258710911e+10 Pr: 160644(2.26877e+10); Du: 0(1.96082e-06) 972.5s
     308134     3.7369623379e+10 Pr: 174178(3.88516e+10); Du: 0(2.06482e-06) 981.9s
     309606     3.7411868994e+10 Pr: 143744(1.91608e+10); Du: 0(2.1986e-06) 987.5s
     310957     3.7478475221e+10 Pr: 96993(6.73304e+09); Du: 0(2.20373e-06) 992.7s
     313580     3.7551539202e+10 Pr: 81741(2.91594e+09); Du: 0(2.02754e-06) 1002.4s
     328663     3.7904949111e+10 Pr: 130975(6.05624e+09); Du: 0(1.81942e-06) 1056.4s
     343870     3.8081103295e+10 Pr: 64050(8.69984e+08); Du: 0(1.76899e-06) 1110.6s
     351379     3.8100505607e+10 Pr: 0(0); Du: 0(2.9576e-10) 1136.2s

Performed postsolve
Solving the original LP from the solution after postsolve

INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 262578 primals, 603907 duals
Objective: 3.81e+10
Solver model: available
Solver message: Optimal

Model name          : linopy-problem-kox2ect8
Model status        : Optimal
Simplex   iterations: 351379
Objective value     :  3.8100505607e+10
P-D objective error :  7.6493176783e-14
HiGHS run time      :       1136.47

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-ext-p-lower, Generator-ext-p-upper, Link-ext-p-lower, Link-ext-p-upper, StorageUnit-ext-p_dispatch-lower, StorageUnit-ext-p_dispatch-upper, StorageUnit-ext-p_store-lower, StorageUnit-ext-p_store-upper, StorageUnit-ext-state_of_charge-lower, StorageUnit-ext-state_of_charge-upper, StorageUnit-energy_balance were not assigned to the network.

('ok', 'optimal')

In [8]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_nom_set,p_min_pu,...,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt
name,,,,,,,,,,,,,,,,,,,,,
wind_reg1,reg1,Slack,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,53353.933234
solar_reg1,reg1,PQ,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,69733.676497
backup_reg1,reg1,PQ,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,139.605041
wind_reg2,reg2,Slack,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,-0.000000
solar_reg2,reg2,PQ,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,29543.725798
backup_reg2,reg2,PQ,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,5942.521706
wind_reg3,reg3,Slack,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,26301.400149
solar_reg3,reg3,PQ,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,20505.239449
backup_reg3,reg3,PQ,,0.0,0.0,True,0.0,inf,NaN,0.0,...,0,0,1,0,NaN,NaN,NaN,NaN,1.0,8477.603968

In [9]:
n.links

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,shut_down_cost,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,p_nom_opt
name,,,,,,,,,,,,,,,,,,,,,
tx_reg1_reg2,reg1,reg2,,AC,1.0,True,0,inf,0.0,0.0,...,0.0,0,0,1,0,NaN,NaN,NaN,NaN,11487.598290
tx_reg1_reg3,reg1,reg3,,AC,1.0,True,0,inf,0.0,0.0,...,0.0,0,0,1,0,NaN,NaN,NaN,NaN,12514.054959
tx_reg2_reg3,reg2,reg3,,AC,1.0,True,0,inf,0.0,0.0,...,0.0,0,0,1,0,NaN,NaN,NaN,NaN,367.388113

In [12]:
n.storage_units

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_nom_set,p_min_pu,...,state_of_charge_initial_per_period,state_of_charge_set,cyclic_state_of_charge,cyclic_state_of_charge_per_period,max_hours,efficiency_store,efficiency_dispatch,standing_loss,inflow,p_nom_opt
name,,,,,,,,,,,,,,,,,,,,,
battery4h_reg1,reg1,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.92,0.92,0.0,0.0,3796.783708
ldes_24h_reg1,reg1,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,24.0,0.80,0.80,0.0,0.0,23961.936407
battery4h_reg2,reg2,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.92,0.92,0.0,0.0,5586.585948
ldes_24h_reg2,reg2,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,24.0,0.80,0.80,0.0,0.0,3433.321808
battery4h_reg3,reg3,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.92,0.92,0.0,0.0,-0.000000
ldes_24h_reg3,reg3,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,24.0,0.80,0.80,0.0,0.0,7606.960843